v1.0.22

diff --git a/.github/workflows/create_module.yml b/.github/workflows/create_module.yml
--- a/.github/workflows/create_module.yml
+++ b/.github/workflows/create_module.yml
@@ -26,6 +26,7 @@ jobs:
           echo "INFO     | Building required variables."
           workspace_name=$(echo "${EVENT_CONTEXT}" | jq -r ".repository.name")
           workspace_name="${workspace_name,,}"
+          echo "workspace_name=${workspace_name}" >> $GITHUB_OUTPUT
           echo "INFO     | Workspace name: ${workspace_name}"
           tfc_api_url="https://app.terraform.io/api/v2"
           auth_header="Authorization: Bearer ${TF_API_TOKEN}"
@@ -33,8 +34,6 @@ jobs:
           echo "INFO     | Running API call to get workspace ID."
           workspace_id=$(curl -sS -H "${auth_header}" -H "${content_header}" -L "${tfc_api_url}/organizations/${{ env.TF_CLOUD_ORGANIZATION }}/workspaces/${workspace_name}" | jq -r '.data."id"')
           if [[ "${workspace_id}" != "null" ]]; then
-            echo "INFO     | Workspace name: ${workspace_name}"
-            echo "workspace_name=${workspace_name}" >> $GITHUB_OUTPUT
             echo "INFO     | Workspace ID: ${workspace_id}"
             echo "workspace_id=${workspace_id}" >> $GITHUB_OUTPUT
           else
@@ -51,15 +50,20 @@ jobs:
           content_header="Content-Type: application/vnd.api+json"
           echo "INFO     | Running API call to get variable id."
           variable_id=$(curl -sS -H "${auth_header}" -H "${content_header}" -L "${tfc_api_url}/workspaces/${{ steps.get_workspace_id.outputs.workspace_id }}/vars" | jq '.data[] | select(.attributes.key == "${{ env.TF_VARIABLE }}" ) | .id')
-          echo "INFO     | Running API call to get variable value."
-          variable_value=$(curl -sS -H "${auth_header}" -H "${content_header}" -L "${tfc_api_url}/workspaces/${{ steps.get_workspace_id.outputs.workspace_id }}/vars" | jq '.data[] | select(.attributes.key == "${{ env.TF_VARIABLE }}" ) | .attributes.value')
-          if [[ "${variable_id}" != "null" && "${variable_value}" != "null" ]]; then
+          if [[ "${variable_id}" != "null" ]]; then
             echo "INFO     | Variable ID: ${variable_id}"
             echo "variable_id=${variable_id}" >> $GITHUB_OUTPUT
+          else
+            echo "ERROR    | Unable to get variable id."
+            exit 1
+          fi          
+          echo "INFO     | Running API call to get variable value."
+          variable_value=$(curl -sS -H "${auth_header}" -H "${content_header}" -L "${tfc_api_url}/workspaces/${{ steps.get_workspace_id.outputs.workspace_id }}/vars" | jq '.data[] | select(.attributes.key == "${{ env.TF_VARIABLE }}" ) | .attributes.value')
+          if [[ "${variable_value}" != "null" ]]; then
             echo "INFO     | Variable value: ${variable_value}"
             echo "variable_value=${variable_value}" >> $GITHUB_OUTPUT
           else
-            echo "ERROR    | Unable to get variable id and value."
+            echo "ERROR    | Unable to get variable value."
             exit 1
           fi
 
@@ -71,9 +75,9 @@ jobs:
           content_header="Content-Type: application/vnd.api+json"
           variable_value=$(echo -e "${{ steps.get_variable.outputs.variable_value }}")
           if [[ "${{ github.event.inputs.module_name }}" =~ ^terraform-[a-zA-Z]+-[a-zA-Z0-9-]+$ ]]; then
-            echo "INFO     | Module's name use a three-part name format like `terraform-<PROVIDER>-<NAME>` and contain only alphanumeric and hypens."
+            echo "INFO     | Module's name use a three-part name format like \"terraform-<PROVIDER>-<NAME>\" and contain only alphanumeric and hypens."
           else
-            echo "ERROR    | Module name must use a three-part name format like `terraform-<PROVIDER>-<NAME>` and contain only alphanumeric and hypens."
+            echo "ERROR    | Module name must use a three-part name format like \"terraform-<PROVIDER>-<NAME>\" and contain only alphanumeric and hypens."
             exit 1
           fi
           if [[ "${variable_value}" =~ ^\[.*\]$ ]]; then
@@ -81,7 +85,7 @@ jobs:
             echo "INFO     | Adding new module's name into the array."
             variable_value="${variable_value::-1}, \"${{ github.event.inputs.module_name }}\"]"
             echo "${variable_value}"
-            echo "INFO     | Converting `\"` into `\\"`."
+            echo "INFO     | Converting \\\" into \\\\"."
             variable_value=${variable_value//\"/\\\"}
             echo "${variable_value}"
           else
