v1.0.22

diff --git a/.github/workflows/create_module.yml b/.github/workflows/create_module.yml
--- a/.github/workflows/create_module.yml
+++ b/.github/workflows/create_module.yml
@@ -57,11 +57,11 @@ jobs:
             exit 1
           fi
           variable_id=$(echo "${run}" | jq '.data[] | select(.attributes.key == "${{ env.TF_VARIABLE }}" ) | .id')
-          echho -e "${ variable_id}"
+          echho -e "${variable_id}"
           variable_value=$(echo "${run}" | jq '.data[] | select(.attributes.key == "${{ env.TF_VARIABLE }}" ) | .attributes.value')
           echho -e "${variable_value}"
           variable_id=$(curl -sS -H "${auth_header}" -H "${content_header}" -L "${tfc_api_url}/workspaces/${{ steps.get_workspace_id.outputs.workspace_id }}/vars" | jq '.data[] | select(.attributes.key == "${{ env.TF_VARIABLE }}" ) | .id')
-          echho -e "${ variable_id}"
+          echho -e "${variable_id}"
           variable_value=$(curl -sS -H "${auth_header}" -H "${content_header}" -L "${tfc_api_url}/workspaces/${{ steps.get_workspace_id.outputs.workspace_id }}/vars" | jq '.data[] | select(.attributes.key == "${{ env.TF_VARIABLE }}" ) | .attributes.value')
           echho -e "${variable_value}"
           if [[ "${variable_id}" != "null" && "${variable_value}" != "null" ]]; then
@@ -94,19 +94,19 @@ jobs:
           json_payload=$(echo "${json_string}" | jq)
           echo "${json_payload}"
           echo "INFO     | Run API call to update variable."
-          {
-            run=$(curl -sS --request PATCH --url "${tfc_api_url}/vars/${{ steps.get_variable.outputs.variable_id }}" \
-            --header "${auth_header}" --header "${content_header}" --data "${json_payload}")
-            if ! [[ "${run}" =~ "{\"data\":" ]]; then
-              echo "ERROR    | Unable to update variable."
-              echo "${run}"
-              exit 1
-            fi
-          } ||
-          {
-            echo "ERROR    | Unable to update variable."
-            exit 1
-          }
+          # {
+          #   run=$(curl -sS --request PATCH --url "${tfc_api_url}/vars/${{ steps.get_variable.outputs.variable_id }}" \
+          #   --header "${auth_header}" --header "${content_header}" --data "${json_payload}")
+          #   if ! [[ "${run}" =~ "{\"data\":" ]]; then
+          #     echo "ERROR    | Unable to update variable."
+          #     echo "${run}"
+          #     exit 1
+          #   fi
+          # } ||
+          # {
+          #   echo "ERROR    | Unable to update variable."
+          #   exit 1
+          # }
 
       # - uses: actions/checkout@v4
 
