v1.0.22

diff --git a/.github/workflows/create_module.yml b/.github/workflows/create_module.yml
--- a/.github/workflows/create_module.yml
+++ b/.github/workflows/create_module.yml
@@ -85,17 +85,18 @@ jobs:
           else
             echo "ERROR    | Variable is not an array."
             exit 1
-          fi          
+          fi
+          if ! [[ "${variable_value}" =~ "${{ github.event.inputs.module_name }}" ]]; then
+            echo "ERROR    | Module's name is already in use.
+            exit 1
+          fi
           echo "INFO     | Adding new module's name into the array."
           variable_value="${variable_value::-1}, \"${{ github.event.inputs.module_name }}\"]"
-          echo "${variable_value}"
           echo "INFO     | Converting \\\" into \\\\\"."
           variable_value=${variable_value//\"/\\\"}
-          echo "${variable_value}"
           echo "INFO     | Building JSON payload."
           json_string='{"data":{"id":"'"${{ steps.get_variable.outputs.variable_id }}"'","attributes":{"value":"'"${variable_value}"'"},"type":"vars"}}'
           json_payload=$(echo "${json_string}" | jq)
-          echo "${json_payload}"
           echo "INFO     | Running API call to update variable."
           {
             run=$(curl -sS --request PATCH --url "${tfc_api_url}/vars/${{ steps.get_variable.outputs.variable_id }}" \
