v1.0.22

diff --git a/.github/workflows/create_module.yml b/.github/workflows/create_module.yml
--- a/.github/workflows/create_module.yml
+++ b/.github/workflows/create_module.yml
@@ -80,18 +80,18 @@ jobs:
             echo "ERROR    | Module's name must use a three-part name format like \"terraform-<PROVIDER>-<NAME>\" and contain only alphanumeric and hypens."
             exit 1
           fi
-          if [[ "${variable_value}" =~ ^\[.*\]$ ]]; then
-            echo "INFO     | Variable is an array."
-            echo "INFO     | Adding new module's name into the array."
-            variable_value="${variable_value::-1}, \"${{ github.event.inputs.module_name }}\"]"
-            echo "${variable_value}"
-            echo "INFO     | Converting \\\" into \\\\"."
-            variable_value=${variable_value//\"/\\\"}
-            echo "${variable_value}"
-          else
-            echo "ERROR    | Variable is not an array."
-            exit 1
-          fi
+          # if [[ "${variable_value}" =~ ^\[.*\]$ ]]; then
+          #   echo "INFO     | Variable is an array."
+          #   echo "INFO     | Adding new module's name into the array."
+          #   variable_value="${variable_value::-1}, \"${{ github.event.inputs.module_name }}\"]"
+          #   echo "${variable_value}"
+          #   echo "INFO     | Converting \\\" into \\\\"."
+          #   variable_value=${variable_value//\"/\\\"}
+          #   echo "${variable_value}"
+          # else
+          #   echo "ERROR    | Variable is not an array."
+          #   exit 1
+          # fi
           
           # echo "${variable_value}"
           # echo "INFO     | Build JSON payload."
